select * from students;
ALTER TABLE students ADD COLUMN certificate VARCHAR(255);
UPDATE Students SET certificate = 'Java Certification' WHERE id = 1;
UPDATE Students SET certificate = 'Data Science Certificate' WHERE id = 2;
UPDATE Students SET certificate = 'Web Development Certificate' WHERE id = 3;
UPDATE Students SET certificate = 'AWS Certified Solutions Architect' WHERE id = 4;
UPDATE Students SET certificate = 'Machine Learning Certificate' WHERE id = 5;
UPDATE Students SET certificate = 'Database Management Certificate' WHERE id = 6;
UPDATE Students SET certificate = 'Cybersecurity Fundamentals' WHERE id = 7;
UPDATE Students SET certificate = 'Cloud Computing Certification' WHERE id = 8;
UPDATE Students SET certificate = 'Python Programming Certificate' WHERE id = 9;
UPDATE Students SET certificate = 'Big Data Analytics Certificate' WHERE id = 10;
UPDATE Students SET certificate = 'Networking Essentials Certificate' WHERE id = 11;
UPDATE Students SET certificate = 'DevOps Engineering Certificate' WHERE id = 12;
